// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use local development URLs when in development mode
const SUPABASE_URL = import.meta.env.DEV
  ? "http://127.0.0.1:54321"
  : "https://ppuaolihdmnaofqlyvzx.supabase.co";

const SUPABASE_PUBLISHABLE_KEY = import.meta.env.DEV
  ? "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwdWFvbGloZG1uYW9mcWx5dnp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxOTU3NzgsImV4cCI6MjA3Mzc3MTc3OH0.PqjHcAruzasooi7bbnqOC_GgTR6-t-4kCKxs2LkgP5w"
  : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwdWFvbGloZG1uYW9mcWx5dnp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxOTU3NzgsImV4cCI6MjA3Mzc3MTc3OH0.PqjHcAruzasooi7bbnqOC_GgTR6-t-4kCKxs2LkgP5w";

// Import the supabase client like this:
//import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});